---
- name: Install comprehensive development environment on Linux
  hosts: localhost
  become: yes  # This allows the playbook to run with sudo privileges

  vars:
    jetbrains_toolbox_version: 1.28.1.15219
    jetbrains_toolbox_download_url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
    jetbrains_toolbox_install_dir: "/opt/jetbrains-toolbox"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure apt-file is installed
      apt:
        name: apt-file
        state: present

    # Vivaldi Browser
    - name: Add Vivaldi repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/vivaldi-browser.gpg] https://repo.vivaldi.com/stable/deb/ stable main
        state: present

    - name: Add Vivaldi GPG key
      apt_key:
        url: https://repo.vivaldi.com/stable/linux_signing_key.pub
        keyring: /usr/share/keyrings/vivaldi-browser.gpg
        state: present

    - name: Install Vivaldi browser
      apt:
        name: vivaldi-stable
        state: present

    # Synology Drive
    - name: Download Synology Drive
      get_url:
        url: "https://global.download.synology.com/download/Utility/SynologyDriveClient/{{ synology_drive_version }}/Ubuntu/Installer/x86_64/synology-drive-client-{{ synology_drive_version }}.x86_64.deb"
        dest: "/tmp/synology-drive-client.deb"
        mode: '0644'

    - name: Install Synology Drive
      apt:
        deb: "/tmp/synology-drive-client.deb"
        state: present

    # Discord
    - name: Add Discord repository
      apt_repository:
        repo: deb [arch=amd64] https://discord.com/api/download?platform=linux&format=deb stable main
        state: present

    - name: Install Discord
      apt:
        name: discord
        state: present

     # Spotify
    - name: Add Spotify repository signing key
      apt_key:
        url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
        state: present

    - name: Add Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify

    - name: Install Spotify
      apt:
        name: spotify-client
        state: present
        update_cache: yes


    # Steam
    - name: Install Steam
      apt:
        name: steam
        state: present

    # BlueMail
    - name: Add BlueMail repository
      apt_repository:
        repo: deb https://download.bluemail.me/BlueMail/deb/stable main
        state: present

    - name: Add BlueMail GPG key
      apt_key:
        url: https://download.bluemail.me/BlueMail/gpg/Key.gpg
        state: present

    - name: Install BlueMail
      apt:
        name: bluemail
        state: present

    # NVIDIA GPU drivers
    - name: Add NVIDIA GPU PPA
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        state: present

    - name: Update apt cache after adding NVIDIA PPA
      apt:
        update_cache: yes

    - name: Install NVIDIA drivers
      apt:
        name: 
          - nvidia-driver-latest
          - nvidia-settings
        state: present

    - name: Install CUDA toolkit
      apt:
        name: nvidia-cuda-toolkit
        state: present

    # JetBrains Toolbox and IDEs
    - name: Install dependencies for JetBrains Toolbox
      apt:
        name:
          - libfuse2
          - fuse
        state: present

    - name: Create JetBrains Toolbox installation directory
      file:
        path: "{{ jetbrains_toolbox_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download JetBrains Toolbox
      get_url:
        url: "{{ jetbrains_toolbox_download_url }}"
        dest: "/tmp/jetbrains-toolbox.tar.gz"
        mode: '0644'

    - name: Extract JetBrains Toolbox
      unarchive:
        src: "/tmp/jetbrains-toolbox.tar.gz"
        dest: "{{ jetbrains_toolbox_install_dir }}"
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Create symbolic link for JetBrains Toolbox
      file:
        src: "{{ jetbrains_toolbox_install_dir }}/jetbrains-toolbox"
        dest: "/usr/local/bin/jetbrains-toolbox"
        state: link

    - name: Run JetBrains Toolbox to start installation
      command: /usr/local/bin/jetbrains-toolbox
      async: 300
      poll: 0
      become: no

    - name: Wait for JetBrains Toolbox to initialize (30 seconds)
      pause:
        seconds: 30

    - name: Install CLion
      command: /usr/local/bin/jetbrains-toolbox install clion
      become: no

    - name: Install PyCharm Professional
      command: /usr/local/bin/jetbrains-toolbox install pycharm-professional
      become: no

    - name: Install IntelliJ IDEA Ultimate
      command: /usr/local/bin/jetbrains-toolbox install intellij-idea-ultimate
      become: no

    # Final system reboot
    - name: Reboot the system
      reboot:
